### ISSUE TITLE
contrib repo

### ISSUE THREAD

**Issue by drKnoxy** [tylerchilds/cutestrap#27]
I thought it might be cool to start a contrib repo under cutestrap user where the public can add modules without it being part of the base build. This keeps the core light, but has easy modules to pull in. It would mean probably declaring vars at the top of each component file though.

My big two additions
- navbar / nav
- cards
- buttons additional
  - primary, secondary, warn
  - outline
  - lg, sm
  - block

**Comment by tylerchilds** [comment]
I've been thinking about this for a while now.

For Cutestrap Two, I've added almost all of those buttons.

Instead of a contrib repo, I'm thinking we can do a snippets section, starting as a single page for now with some context buttons: http://www.cutestrap.com/snippets/ Let me know what you think!
