### ISSUE TITLE
Select arrow not clickable

### ISSUE THREAD

**Issue by rotsee** [tylerchilds/cutestrap#49]
The css arrow in select boxes (`.field select+.label::after`) is not clickable (Chrome, Firefox, others). This is an issue to users who aim for that very arrow when trying to use the menu, and give up if that doesn't work (a behavior seen in real usage testing).

I _think_ the solution might be as easy as adding an `pointer-events: none;` (well, not for Internet Explorer, but Cutestrap forms don't really work with IE anyway)

**Comment by tylerchilds** [comment]
Just checked, `pointer-events: none;` will definitely solve this. I'll take care of this with my next couple fixes, probably tomorrow AM.

Thanks! :)

**Comment by tylerchilds** [comment]
Resolved in the latest patch: `2.0.0-4`. Sorry for the delay!

**Comment by dallanlee** [comment]
I was going to PR this fix as well since the site is still using an older version without the fix. Glad it's already taken care of. However, I was thinking, why not apply `pointer-events: none` to `select + .label` so that the behavior of being able to click *anywhere* in the `<label>`/`<select>` will focus the `<select>` like the other form elements (`<input>`, `<textarea>`) do? 🤷🏼‍♂️
